workflows:
  android-release:
    name: Android Release (CCF)
    environment:
      node: 20
      java: 17
      vars:
        PACKAGE_NAME: "com.emscodesim.ccf"
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Capacitor sync/copy
        script: |
          npx cap sync android
          npx cap copy android

      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
