workflows:
  android-release:
    name: Android Release (CCF)
    environment:
      node: 22
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor sync/copy
        script: |
          npx cap sync android
          npx cap copy android
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
